### ISSUE TITLE
Error "stat: missing operand"

### ISSUE THREAD

**Issue by Iwios** [moerphin/vzdump2influx#10]
Hello,
I've running shell script, and this is the return  I have:

INFO: stat: missing operand
INFO: Try 'stat --help' for more information.
INFO:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
INFO:                                  Dload  Upload   Total   Spent    Left  Speed
INFO:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
INFO: 100   218  100   143  100    75   1554    815 --:--:-- --:--:-- --:--:--  2369
INFO: {"code":"invalid","message":"unable to parse 'proxmox,host=srv-reverseproxy-1,location= success=1,duration=0,speed=,size=': missing tag value"}
INFO: Backup job finished successfully
TASK OK

**Comment by Iwios** [comment]
And if I enable debug :

INFO: Backup finished at 2023-02-15 22:32:47
INFO: cp: missing destination file operand after '/tmp/1'
INFO: Try 'cp --help' for more information.
INFO: stat: missing operand
INFO: Try 'stat --help' for more information.
INFO:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
INFO:                                  Dload  Upload   Total   Spent    Left  Speed
INFO:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
INFO: 100   218  100   143  100    75   1554    815 --:--:-- --:--:-- --:--:--  2369
INFO: {"code":"invalid","message":"unable to parse 'proxmox,host=srv-reverseproxy-1,location= success=1,duration=0,speed=,size=': missing tag value"}
INFO: Backup job finished successfully
TASK OK

**Comment by moerphin** [comment]
Hello,
I think it's fixed now. Please try it.
Don't forget to fill the "location" variable.
