### ISSUE TITLE
Error PUSH API : missing field value

### ISSUE THREAD

**Issue by Iwios** [moerphin/vzdump2influx#11]
Hello,
I'v update script with the last version. Unfortunatly, another error :

INFO: starting new backup job: vzdump 102 --storage PBS1 --node prx1 --remove 0 --mode snapshot --notes-template '{{guestname}}'
INFO: Starting Backup of VM 102 (qemu)
INFO: Backup started at 2023-02-16 15:58:02
INFO: status = running
INFO: VM Name: srv-reverseproxy-1
INFO: include disk 'scsi0' 'Data1:vm-102-disk-0' 20G
INFO: backup mode: snapshot
INFO: ionice priority: 7
INFO: creating Proxmox Backup Server archive 'vm/102/2023-02-16T14:58:02Z'
INFO: issuing guest-agent 'fs-freeze' command
INFO: enabling encryption
INFO: issuing guest-agent 'fs-thaw' command
INFO: started backup task '120bc6ba-0a64-4a7d-b56b-e53d33d2a387'
INFO: resuming VM again
INFO: scsi0: dirty-bitmap status: OK (92.0 MiB of 20.0 GiB dirty)
INFO: using fast incremental mode (dirty-bitmap), 92.0 MiB dirty of 20.0 GiB total
INFO: 100% (92.0 MiB of 92.0 MiB) in 2s, read: 46.0 MiB/s, write: 44.0 MiB/s
INFO: backup was done incrementally, reused 19.91 GiB (99%)
INFO: transferred 92.00 MiB in 2 seconds (46.0 MiB/s)
INFO: adding notes to backup
INFO: Finished Backup of VM 102 (00:00:02)
INFO: Backup finished at 2023-02-16 15:58:04
INFO: cp: missing destination file operand after '/tmp/1676559484'
INFO: Try 'cp --help' for more information.
INFO: stat: cannot statx 'vm/102/2023-02-16T14:58:02Z': No such file or directory
INFO:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
INFO:                                  Dload  Upload   Total   Spent    Left  Speed
INFO:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
INFO: 100    78    0     0  100    78      0   1300 --:--:-- --:--:-- --:--:--  1278
INFO: 100   226  100   148  100    78   1574    829 --:--:-- --:--:-- --:--:--  2378
INFO: {"code":"invalid","message":"unable to parse 'proxmox,host=srv-reverseproxy-1,location=OVH success=1,duration=0,speed=,size=': missing field value"}
INFO: Backup job finished successfully
TASK OK

I have a proxmox Backup server where I made backup, this is maybe why script not work ?

**Comment by moerphin** [comment]
Yeah, it seems incompatible to PBS. Can you send me logs for incremental and full backup? (Currently I don't have any PBS.)

**Comment by moerphin** [comment]
New version, please try it.

**Comment by Iwios** [comment]
I try new version, same error :
INFO: {"code":"invalid","message":"unable to parse 'proxmox,host=srv-reverseproxy-1,location=FR success=1,duration=0,speed=,size=': missing field value"}

**Comment by moerphin** [comment]
OK, I need to install a PBS instance for debugging.

**Comment by Iwios** [comment]
Ok. If you need help for something tell me :)

**Comment by Iwios** [comment]
Hello, Have you an update for this script with PBS?

**Comment by Iwios** [comment]
Hello @moerphin 
How I can help you to debug and add missing conf for pbs ?

**Comment by Iwios** [comment]
I just retry and the process working :)
Thank for your work !!
