### ISSUE TITLE
Support for transfer-speed

### ISSUE THREAD

**Issue by heinrich76** [moerphin/vzdump2influx#3]
Hi moerphin,

we are using you script successfully with grafana. It is working great. Is it possible to add the transfer-speed to your script?

Regards,
Heinrich

**Comment by moerphin** [comment]
Hello,

I hope I can help you to solve this problem.
Do you think countinous logging along the whole backup process, or just an average transfer speed per backup?

**Comment by heinrich76** [comment]
Hi!
Thanks for your fast reply!
The average transfer speed would be fine (it is in the infobox when the backup is done). 
![backup01](https://user-images.githubusercontent.com/38105483/38413848-28ba44c8-398d-11e8-8636-33820530d8a5.jpg)

Heinrich

**Comment by moerphin** [comment]
Transfer speed added, new grafana dashboard published.
