### ISSUE TITLE
No transfer speed LXC

### ISSUE THREAD

**Issue by jstgnkl** [moerphin/vzdump2influx#4]
VM transfer speed works fine, LXC stays at 0 MB/s. Any idea what to change in the grafana metrics?

[
![image](https://user-images.githubusercontent.com/9056070/46557882-b1c2bf00-c8eb-11e8-9b40-521a613b3522.png)
](url)

The other information works excellent!

**Comment by moerphin** [comment]
I will fix it until end of october (between 20. october and 4. november).
Thank you!

**Comment by moerphin** [comment]
Please download the new script. I fixed it.
