### ISSUE TITLE
Missing field value

### ISSUE THREAD

**Issue by StefanescuCristian** [moerphin/vzdump2influx#6]
Hello,

Running this on the latest proxmox version (pve-manager/6.2-10/a20769ed (running kernel: 5.4.44-2-pve)) gives the following error:

cat /tmp/tst
```
HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: b9830bcb-c83e-11ea-9a95-0242ac140003
X-Influxdb-Build: OSS
X-Influxdb-Error: unable to parse 'proxmox,host=unifi,location=RO success=1,duration=236,speed=,size=6154757022': missing field value
X-Influxdb-Version: 1.8.1
X-Request-Id: b9830bcb-c83e-11ea-9a95-0242ac140003
Date: Fri, 17 Jul 2020 15:03:51 GMT
Content-Length: 128

{"error":"unable to parse 'proxmox,host=unifi,location=RO success=1,duration=236,speed=,size=6154757022': missing field value"}
```

It looks like the speed variable is not read from some reason. How can I help with debugging?

**Comment by moerphin** [comment]
Hello,
please insert this code at line 17. (In a new line.)
``cp ${LOGFILE} /tmp/`date +%s` ``
This line will save log files to your /tmp dir (filename in epoch time format). Please send me one of these logs (pastebin?), or just the summary lines.
(After you sent it, delete this line from the script.)
Thank you!

**Comment by StefanescuCristian** [comment]
Hello,

Here is the output: https://pastebin.com/StNHH2t6

**Comment by moerphin** [comment]
OK, I found a problem in the regular expression and fixed it. Can you try it please?

Edit: I broke the LXC transfer speed with the last fix, so rewrote the expression again. Now it's working. Please send some feedback if you tried it.

**Comment by StefanescuCristian** [comment]
Hello,

The following error occured now:

INFO: Backup is sparse: 60% (19.39 GiB) zero data
INFO: archive file size: 4.78GB
INFO: Finished Backup of VM 100 (00:03:32)
INFO: Backup finished at 2020-07-22 11:57:16
INFO: /usr/local/bin/vzdump2influx.sh: line 26: 154.6: syntax error: invalid arithmetic operator (error token is ".6")
INFO: Backup job finished successfully
TASK OK

**Comment by StefanescuCristian** [comment]
I think that the problem is that by doing $(( )) you're telling bash to use some math functionality. The thing is that bash doesn't know floating point math. I think that is safe we can exclude the decimals of the speed variable by using sed after the grep. Something like ```sed -e 's/\..*//g'```

```
SPEED=$((`cat ${LOGFILE} | grep -o -P "(?<=seconds \().*(?= MB\/s| MiB\/s)" | sed -e 's/\..*//g'`))
```

But by doing that now I have another error in tst file:

```
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 4d72f18f-cbfc-11ea-9520-0242ac140003
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.1
X-Request-Id: 4d72f18f-cbfc-11ea-9520-0242ac140003
Date: Wed, 22 Jul 2020 09:18:27 GMT
```

I'll try to debug more later.

**Comment by moerphin** [comment]
The second one looks good.
But I uploaded an other version, this will keep the float.

**Comment by StefanescuCristian** [comment]
Tested with the latest version, but something is wrong, and I can't tell what.

The script seems that works now (BTW, just a little typo on the last line: shouldn't $TRAFILE be $TARFILE?) but the post still fails.

I don't know if it's my influx's fault or not.

```
/usr/bin/curl -s -i -XPOST -u influxuser:influxpass 'http://192.168.88.17:8086/write?db=telegraf' --data-binary 'proxmox,host=prx2,location=RO success=1,duration=190,speed=172.5,size=522'

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 33bfa6d2-cc17-11ea-83d8-0242ac140003
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.1
X-Request-Id: 33bfa6d2-cc17-11ea-83d8-0242ac140003
Date: Wed, 22 Jul 2020 12:31:01 GMT
```

Since the original issue was that the speed variable doesn't get set and now it does, I guess we can close this.

**Comment by moerphin** [comment]
(Fixed the typo, thanks.)
I can't see any errors in your post. Your POST works fine. My POST's output looks similar, and my data is in the db:
`/usr/bin/curl -s -i -XPOST -u someuser:somepass "http://someip:someport/write?db=somedb" --data-binary  "test,host=test1,location=testlo success=1,duration=120,speed=12.5,size=555"`

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 14b4e254-cc19-11ea-8fd5-6a343e22bd34
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.10
X-Request-Id: 14b4e254-cc19-11ea-8fd5-6a343e22bd34
Date: Wed, 22 Jul 2020 12:44:28 GMT
